In [42]:
import scipy.io as sio
import numpy as np
import h5py

In [43]:
data = sio.loadmat('garbage_crop_37.mat')['garbage_crop_37']
print(data.shape)
target = sio.loadmat('garbage_crop_37_gt.mat')['garbage_crop_37_gt']
print(target.shape)

(561, 591, 63)
(561, 591)


In [36]:
np.unique(target)

array([0, 2, 3], dtype=uint8)

In [37]:
Height,Width = target.shape
print(Height,Width)

561 591


In [38]:
for h in range(Height):
    for w in range(Width):
        if target[h][w] == 0:
            target[h][w] = 0
        if target[h][w] == 1:
            target[h][w] = 0
        if target[h][w] == 2:
            target[h][w] = 1
        if target[h][w] == 3:
            target[h][w] = 2

In [39]:
np.unique(target)

array([0, 1, 2], dtype=uint8)

In [41]:
sio.savemat('garbage_crop_37_gt.mat', {'garbage_crop_37_gt':target})
gt_data = sio.loadmat('garbage_crop_37_gt.mat')['garbage_crop_37_gt']
print(gt_data.shape)

(561, 591)


### Inference Data

In [50]:
inference_data = sio.loadmat('garbage_crop_37_inference_gt.mat')['garbage_crop_37_inference_gt']

In [51]:
np.unique(inference_data)

array([1, 2], dtype=uint8)

In [46]:
Height,Width = inference_data.shape
print(Height,Width)

561 591


In [47]:
for h in range(Height):
    for w in range(Width):
        if inference_data[h][w] == 2:
            inference_data[h][w] = 1
        if inference_data[h][w] == 3:
            inference_data[h][w] = 2

In [48]:
np.unique(inference_data)

array([1, 2], dtype=uint8)

In [49]:
sio.savemat('garbage_crop_37_inference_gt.mat', {'garbage_crop_37_inference_gt':inference_data})